name: CI - Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./src/JobApplicationMVCApp

      - name: Build the solution
        run: dotnet build ./src/JobApplicationMVCApp --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ./src/JobApplicationMVCAppTests/JobApplicationMVCAppTests.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"